# name: GitHub Actions Build and Deploy Demo
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master

#     - name: Install and Build
#       run: npm install && npm run build
    
#     - name: Deploy
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: dist


name: My Continue Integration
on: 
  push:
    branches: 
    - master
    paths:
    - 'src/**'
env:
  SERVER: production

jobs:
  first-job:
    name: my first job
    runs-on: ubuntu-latest
    steps:
    - name: Output Context
      run: echo $SERVER $NAME_ID
    env:
      NAME_ID: sxx_7258615