# name: GitHub Actions Build and Deploy Demo
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master

#     - name: Install and Build
#       run: npm install && npm run build
    
#     - name: Deploy
#       uses: JamesIves/github-pages-deploy-action@releases/v3
#       with:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: dist


name: Build & Deploy
on:
  push:
    # branches:
    # - master
    tags:
    - v*

jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      uses: actions/setup-node@master
    - run: |
        npm install
        npm run build
        tar -zcvf release.gz ./dist
      

    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@releases/v3
    #   with:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: dist

    - name: Create Release
      id: create-release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with: 
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./release.gz
        asset_name: release.gz
        asset_content_type: application/gz
